version: '3.4'

services:
  webapp:
    image: taskmanagementapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "L5jGhLbKuKUfanrSN"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"